# Generated by Django 4.1.13 on 2024-04-04 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_food_category_en_remove_food_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2002-11-11', verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='food_images/image.png', upload_to='category_images/', verbose_name='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AddField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2002-11-11', verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='food',
            table='foods',
        ),
        migrations.CreateModel(
            name='FoodImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_images/', verbose_name='image')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='foods.food', verbose_name='food_image')),
            ],
            options={
                'verbose_name': 'Food image ',
                'verbose_name_plural': 'Food images ',
                'db_table': 'food_images',
            },
        ),
    ]
