# Generated by Django 4.1.13 on 2024-04-02 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cooking_time',
            field=models.DurationField(default=datetime.timedelta(seconds=75), verbose_name='cooking time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DurationField(default=datetime.timedelta(seconds=180), verbose_name='delivery time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total price'),
        ),
    ]
