# Generated by Django 4.1.13 on 2024-04-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_cooking_time_alter_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cooking_time',
        ),
    ]
