# Generated by Django 4.1.13 on 2024-04-03 07:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='location', blank=True, null=True),
            preserve_default=False,
        ),
    ]
