# Generated by Django 4.1.13 on 2024-04-04 05:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude',
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='SRID=4326;POINT (-74.006 40.7128)', geography=True, srid=4326, verbose_name='location'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_items',
        ),
    ]
