# Generated by Django 4.1.13 on 2024-04-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_latitude_remove_order_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancelled',
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('waiting', 'waiting'), ('preparing', 'preparing'), ('delivering', 'delivering'), ('cancelled', 'cancelled')], default='waiting', max_length=10, verbose_name='state'),
        ),
    ]
