version: '3'

volumes:
  postgres_data: {}
  static_data: {}
  media_data: {}

services:
  web: &web
    container_name: ${PROJECT_NAME}_web
    depends_on:
      - db
    build: .
    volumes:
      - .:/app/
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
    env_file: .env
    command: gunicorn core.wsgi:application --bind 0.0.0.0:${PORT}
    ports:
      - ${PORT}:${PORT}
    restart: always

  db:
    image: postgres:13.4-buster
    container_name: ${PROJECT_NAME}_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    restart: always

  redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis:5.0
    restart: always


  celery_worker:
     <<: *web
     container_name: ${PROJECT_NAME}_worker
     ports: [ ]
     command: celery -A core.celery worker -l INFO
     restart: always

  celery_beat:
     <<: *web
     container_name: ${PROJECT_NAME}_beat
     ports: [ ]
     command: celery -A core.celery beat -l INFO
     restart: always
