# Generated by Django 4.1.13 on 2024-04-02 05:04

import apps.users.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.manager.UserManager()),
            ],
        ),
    ]
