# Generated by Django 4.1.13 on 2024-04-02 13:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(default='2002-11-11', max_length=128, region=None, unique=False, verbose_name='branch_contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_foods',
            field=models.ManyToManyField(related_name='branch_foods', to='foods.food', verbose_name='branch_foods'),
        ),
    ]
