# Generated by Django 4.1.13 on 2024-04-03 08:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_branch_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326, verbose_name='location'),
        ),
    ]
