# Generated by Django 4.1.13 on 2024-04-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_address_en_branch_address_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='longitude',
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branches',
        ),
    ]
