# Generated by Django 4.1.13 on 2024-04-05 04:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0006_remove_branch_latitude_remove_branch_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2002-11-11', verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.CreateModel(
            name='BranchComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='branches.branch', verbose_name='branch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_comments', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'Branch comment ',
                'verbose_name_plural': 'Branch comments ',
                'unique_together': {('branch', 'client')},
            },
        ),
    ]
