# Generated by Django 4.1.13 on 2024-04-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_branch_created_at_branch_updated_at_branchcomments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branchcomments',
            table='branch_comments',
        ),
    ]
