# Generated by Django 4.1.13 on 2024-04-24 08:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_alter_branchcomments_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchcomments',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='area'),
        ),
    ]
